java:
    minVersion: ""
    maxVersion: ""
    customJavaCmd: ""
    jvmArgs:
        - -Xms256m
        - -Xmx1g
server:
    port: 8080
    host: ""
    contexts:
        - /fhir
    env: {}
    maxMemory: 1g
versions: {}
logLevel: info
downloadUrl: https://releases.fhir-guard.org
